[build]
builder = "dockerfile"
dockerfilePath = "apps/backend/Dockerfile"
watchPatterns = ["apps/backend/**"]

[deploy]
startCommand = "./backend"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
